---
- name: Zsh setup
  hosts: all

  pre_tasks:
    - name: Ensure fd-find and fzf are installed.
      become: true
      package:
        name:
          - fd-find
          - fzf
        state: present

  roles:
    - role: gantsign.antigen
      users:
        - username: "{{ hostvars[inventory_hostname]['ansible_user'] }}"
          antigen_libraries:
            - name: oh-my-zsh
          antigen_theme:
            name: kolo
          antigen_bundles:
            - name: git
            - name: fzf
            - name: zsh-autosuggestions
              url: zsh-users/zsh-autosuggestions
            - name: zsh-syntax-highlighting
              url: zsh-users/zsh-syntax-highlighting

  tasks:
    # Copy dotfiles for basic and custom configs
    - name: Copy ~/.zsh-basic file (replace if changed)
      copy:
        src: dotfiles/.zsh-basic
        dest: /home/{{ hostvars[inventory_hostname]['ansible_user'] }}/.zsh-basic
        owner: "{{ hostvars[inventory_hostname]['ansible_user'] }}"
        group: "{{ hostvars[inventory_hostname]['ansible_user'] }}"
        mode: '0644'
        backup: true
    - name: Copy ~/.zsh-custom file (if not exists)
      copy:
        src: dotfiles/.zsh-custom
        dest: /home/{{ hostvars[inventory_hostname]['ansible_user'] }}/.zsh-custom
        owner: "{{ hostvars[inventory_hostname]['ansible_user'] }}"
        group: "{{ hostvars[inventory_hostname]['ansible_user'] }}"
        mode: '0644'
        force: false
    
    # Source dotfiles on ~/.zshrc
    - name: Source ~/.zsh-basic on ~/.zshrc
      lineinfile:
        dest: "/home/{{ hostvars[inventory_hostname]['ansible_user'] }}/.zshrc"
        regexp: "^source ~/.zsh-basic$"
        line: "source ~/.zsh-basic"
    - name: Source ~/.zsh-custom on ~/.zshrc
      lineinfile:
        dest: "/home/{{ hostvars[inventory_hostname]['ansible_user'] }}/.zshrc"
        regexp: "^source ~/.zsh-custom$"
        line: "source ~/.zsh-custom"
